# This script appends the missing content to auto_render.py
# The SAPI f-string issue is fixed by pre-computing wav_path into a variable

lines = [
    '    retries: int = 3,\n',
    ') -> bool:\n',
    '    """Download an image from Pollinations Flux (free, no API key)."""\n',
    '    style = STYLE_SUFFIX.get(channel, DEFAULT_STYLE)\n',
    '    full_prompt = f"{prompt}, {style}"\n',
    '    encoded    = urllib.parse.quote(full_prompt)\n',
    '    url        = POLL_URL.format(prompt=encoded, w=w, h=h, seed=seed)\n',
    '\n',
    '    for attempt in range(retries):\n',
    '        try:\n',
    '            print(f"         Fetching image (attempt {attempt+1}/{retries})…")\n',
    '            req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})\n',
    '            with urllib.request.urlopen(req, timeout=60) as resp:\n',
    '                data = resp.read()\n',
    '            out_path.write_bytes(data)\n',
    '            print(f"         ✓ Image saved ({len(data)//1024} KB)")\n',
    '            return True\n',
    '        except Exception as e:\n',
    '            print(f"         ✗ Attempt {attempt+1} failed: {e}")\n',
    '            if attempt < retries - 1:\n',
    '                time.sleep(3)\n',
    '    return False\n',
    '\n',
    '\n',
    '# ── Fallback image card ────────────────────────────────────────────────────────────────────────────────\n',
    'def make_fallback_card(path: Path, w: int, h: int, bg: list) -> None:\n',
    '    """Create a solid-color fallback image using FFmpeg (no Pillow needed)."""\n',
    '    color = (bg[0] if bg else "#1a1a2e").lstrip("#")\n',
    '    r, g, b = int(color[0:2], 16), int(color[2:4], 16), int(color[4:6], 16)\n',
    '    ffmpeg = find_ffmpeg()\n',
    '    subprocess.run(\n',
    '        [ffmpeg, "-y", "-f", "lavfi",\n',
    '         "-i", f"color=c=#{color}:size={w}x{h}:rate=1",\n',
    '         "-frames:v", "1", str(path)],\n',
    '        capture_output=True,\n',
    '    )\n',
    '\n',
    '\n',
    '# ── Render one scene → MP4 clip ────────────────────────────────────────────────\n',
    'def render_scene(\n',
    '    img_path: Path,\n',
    '    audio_path: Path,\n',
    '    clip_path: Path,\n',
    '    dur: float,\n',
    '    w: int,\n',
    '    h: int,\n',
    '    ffmpeg: str,\n',
    '    zoom: float = ZOOM,\n',
    ') -> bool:\n',
    '    """Ken Burns zoom + TTS audio → MP4 clip."""\n',
    '    zoom_end   = 1.0 + zoom * dur * FPS\n',
    "    vf = (\n",
    "        f\"scale={w*2}:{h*2},\"\n",
    "        f\"zoompan=z='min(zoom+{zoom:.6f},{zoom_end:.4f})':d={int(dur*FPS)}:\"\n",
    "        f\"x='iw/2-(iw/zoom/2)':y='ih/2-(ih/zoom/2)':s={w}x{h}:fps={FPS},\"\n",
    "        f\"format=yuv420p\"\n",
    "    )\n",
    '    cmd = [\n',
    '        ffmpeg, "-y",\n',
    '        "-loop", "1", "-i", str(img_path),\n',
    '        "-i",           str(audio_path),\n',
    '        "-vf",          vf,\n',
    '        "-c:v",         "libx264",\n',
    '        "-preset",      "fast",\n',
    '        "-crf",         "23",\n',
    '        "-c:a",         "aac",\n',
    '        "-b:a",         "192k",\n',
    '        "-shortest",\n',
    '        "-movflags",    "+faststart",\n',
    '        str(clip_path),\n',
    '    ]\n',
    '    result = subprocess.run(cmd, capture_output=True, timeout=300)\n',
    '    return result.returncode == 0\n',
    '\n',
    '\n',
    '# ── Concatenate all scene clips → final video ───────────────────────────────────\n',
    'def concat_scenes(scene_files: list, out_path: Path, ffmpeg: str) -> None:\n',
    '    """Write a concat list and merge all scene clips."""\n',
    '    list_path = out_path.parent / "concat_list.txt"\n',
    '    with open(list_path, "w") as f:\n',
    '        for sf in scene_files:\n',
    "            f.write(f\"file '{sf}'\\n\")\n",
    '    subprocess.run(\n',
    '        [ffmpeg, "-y", "-f", "concat", "-safe", "0",\n',
    '         "-i", str(list_path),\n',
    '         "-c", "copy", str(out_path)],\n',
    '        capture_output=True,\n',
    '        timeout=600,\n',
    '    )\n',
    '\n',
    '\n',
    '# ── Optional music mix ─────────────────────────────────────────────────────────────\n',
    'def mix_music(video_path: Path, music_path: Path, out_path: Path, ffmpeg: str) -> None:\n',
    '    """Mix background music under narration (narration wins)."""\n',
    '    dur = get_duration(video_path, ffmpeg)\n',
    '    subprocess.run(\n',
    '        [ffmpeg, "-y",\n',
    '         "-i", str(video_path),\n',
    '         "-stream_loop", "-1", "-i", str(music_path),\n',
    '         "-filter_complex",\n',
    '         "[1:a]volume=0.12[music];[0:a][music]amix=inputs=2:duration=first[aout]",\n',
    '         "-map", "0:v", "-map", "[aout]",\n',
    '         "-c:v", "copy", "-c:a", "aac", "-b:a", "192k",\n',
    '         "-t", str(dur), str(out_path)],\n',
    '        capture_output=True,\n',
    '        timeout=600,\n',
    '    )\n',
    '\n',
    '\n',
    '# ── Main render loop ─────────────────────────────────────────────────────────────────\n',
    'def main() -> None:\n',
    '    ap = argparse.ArgumentParser(description="Viral Engine — hands-free video pipeline")\n',
    '    ap.add_argument("--episode",      required=True,  help="e.g. GG_EP001, ML_EP002")\n',
    '    ap.add_argument("--skip-images",  action="store_true", help="Reuse cached scene images")\n',
    '    ap.add_argument("--music",        default=None,   help="Path to background music MP3")\n',
    '    ap.add_argument("--portrait",     action="store_true", help="1080x1920 Shorts format")\n',
    '    args = ap.parse_args()\n',
    '\n',
    "    episode_id = args.episode.upper()\n",
    "    channel    = episode_id.split('_')[0]   # GG / ML / LO\n",
    '\n',
    '    w, h = (W_PORT, H_PORT) if args.portrait else (W_LAND, H_LAND)\n',
    '\n',
    '    ffmpeg = find_ffmpeg()\n',
    "    print(f\"\\n{'='*60}\")\n",
    "    print(f\"  VIRAL ENGINE  —  {CHANNEL_LABELS.get(channel, channel)}  —  {episode_id}\")\n",
    "    print(f\"{'='*60}\\n\")\n",
    '\n',
    '    # ── Load episode JSON ─────────────────────────────────────────────────────────────\n',
    '    try:\n',
    '        ep_path = find_episode_json(episode_id)\n',
    '    except FileNotFoundError as exc:\n',
    '        sys.exit(f"ERROR: {exc}")\n',
    '\n',
    '    with open(ep_path, encoding="utf-8") as f:\n',
    '        ep_data = json.load(f)\n',
    '\n',
    '    scenes = ep_data.get("scenes", [])\n',
    '    if not scenes:\n',
    '        sys.exit("ERROR: No scenes found in episode JSON.")\n',
    '\n',
    '    title   = ep_data.get("title", episode_id)\n',
    '    voice   = CHANNEL_VOICE.get(channel, "en-US-ChristopherNeural")\n',
    '    rate    = CHANNEL_RATE.get(channel,  "-5%")\n',
    '\n',
    '    print(f"  Episode : {title}")\n',
    '    print(f"  Scenes  : {len(scenes)}")\n',
    '    print(f"  Voice   : {voice}  ({rate})")\n',
    '    print(f"  Size    : {w}x{h}\\n")\n',
    '\n',
    '    # ── Work directory ─────────────────────────────────────────────────────────────────\n',
    '    work_dir = OUTPUT_DIR / episode_id\n',
    '    work_dir.mkdir(parents=True, exist_ok=True)\n',
    '\n',
    '    renders_dir = BASE_DIR / "renders"\n',
    '    renders_dir.mkdir(exist_ok=True)\n',
    '\n',
    '    final_raw  = work_dir / f"{episode_id}_raw.mp4"\n',
    '    final_out  = renders_dir / f"{episode_id}_final.mp4"\n',
    '\n',
    '    scene_files: list[Path] = []\n',
    '\n',
    '    # ── Scene loop ─────────────────────────────────────────────────────────────────────\n',
    '    for idx, scene in enumerate(scenes):\n',
    '        num    = scene.get("scene_number", idx + 1)\n',
    '        narr   = scene.get("narration",    "")\n',
    '        prompt = scene.get("visual_prompt", "")\n',
    '        stitle = scene.get("title",        f"Scene {num}")\n',
    '        dur    = float(scene.get("duration_sec", 47))\n',
    '        bg     = scene.get("bg_colors",   ["#1a1a2e"])\n',
    '\n',
    '        img_path   = work_dir / f"scene_{num:02d}.jpg"\n',
    '        audio_path = work_dir / f"scene_{num:02d}.mp3"\n',
    '        clip_path  = work_dir / f"scene_{num:02d}.mp4"\n',
    '\n',
    '        print(f"\\n── Scene {num:02d}/{len(scenes)}  [{stitle}] ──")\n',
    '\n',
    '        # Step 1 — Image\n',
    '        if args.skip_images and img_path.exists():\n',
    '            print(f"   [IMG]  Reusing cached {img_path.name}")\n',
    '        else:\n',
    '            local = find_local_image(prompt, stitle, episode_id, num)\n',
    '            if local:\n',
    '                print(f"   [IMG]  Local image → {local.name}")\n',
    '                shutil.copy2(str(local), str(img_path))\n',
    '            else:\n',
    '                print(f"   [IMG]  Pollinations Flux…")\n',
    '                ok = fetch_image(prompt, img_path, seed=num * 13 + idx,\n',
    '                                 channel=channel, w=w, h=h)\n',
    '                if not ok:\n',
    '                    print(f"   [IMG]  Fallback card (all fetches failed)")\n',
    '                    make_fallback_card(img_path, w, h, bg)\n',
    '\n',
    '        # Step 2 — TTS narration\n',
    '        if not audio_path.exists() or audio_path.stat().st_size < 1000:\n',
    '            print(f"   [TTS]  Generating narration…")\n',
    '            try:\n',
    '                import asyncio, edge_tts\n',
    '                async def _tts() -> None:\n',
    '                    comm = edge_tts.Communicate(narr, voice=voice, rate=rate)\n',
    '                    await comm.save(str(audio_path))\n',
    '                asyncio.run(_tts())\n',
    '                print(f"   [TTS]  ✓ {audio_path.name}")\n',
    '            except ImportError:\n',
    '                print("   [TTS]  edge-tts not installed — trying SAPI fallback…")\n',
    '                try:\n',
    '                    wav_str = str(audio_path.with_suffix(".wav"))\n',
    "                    safe_narr = narr.replace(\"'\", \"\")\n",
    '                    subprocess.run(\n',
    '                        ["powershell", "-Command",\n',
    '                         "Add-Type -AssemblyName System.Speech; "\n',
    '                         "$s=New-Object System.Speech.Synthesis.SpeechSynthesizer; "\n',
    "                         f\"$s.SetOutputToWaveFile('{wav_str}'); \"\n",
    "                         f\"$s.Speak('{safe_narr}'); $s.Dispose()\"],\n",
    '                        capture_output=True, timeout=60,\n',
    '                    )\n',
    '                    wav = audio_path.with_suffix(".wav")\n',
    '                    if wav.exists():\n',
    '                        subprocess.run(\n',
    '                            [ffmpeg, "-y", "-i", str(wav), str(audio_path)],\n',
    '                            capture_output=True,\n',
    '                        )\n',
    '                        print(f"   [TTS]  ✓ SAPI fallback {audio_path.name}")\n',
    '                    else:\n',
    '                        _make_silence(audio_path, dur, ffmpeg)\n',
    '                except Exception:\n',
    '                    _make_silence(audio_path, dur, ffmpeg)\n',
    '            except Exception as e:\n',
    '                print(f"   [TTS]  ✗ Failed: {e} — using silence")\n',
    '                _make_silence(audio_path, dur, ffmpeg)\n',
    '        else:\n',
    '            print(f"   [TTS]  Reusing {audio_path.name}")\n',
    '\n',
    '        # Step 3 — Render scene clip\n',
    '        if not clip_path.exists() or clip_path.stat().st_size < 10_000:\n',
    '            print(f"   [VID]  Rendering Ken Burns clip…")\n',
    '            ok = render_scene(img_path, audio_path, clip_path, dur, w, h, ffmpeg)\n',
    '            if ok:\n',
    '                print(f"   [VID]  ✓ {clip_path.name}")\n',
    '            else:\n',
    '                print(f"   [VID]  ✗ render_scene failed for scene {num}")\n',
    '                continue\n',
    '        else:\n',
    '            print(f"   [VID]  Reusing {clip_path.name}")\n',
    '\n',
    '        scene_files.append(clip_path)\n',
    '\n',
    '    # ── Concat all clips ───────────────────────────────────────────────────────────\n',
    '    if not scene_files:\n',
    '        sys.exit("ERROR: No scene clips were produced.")\n',
    '\n',
    '    print(f"\\n── Concatenating {len(scene_files)} clips…")\n',
    '    concat_scenes(scene_files, final_raw, ffmpeg)\n',
    '\n',
    '    # ── Optional music mix ─────────────────────────────────────────────────────────────\n',
    '    if args.music and Path(args.music).exists():\n',
    '        print(f"── Mixing background music: {args.music}…")\n',
    '        mix_music(final_raw, Path(args.music), final_out, ffmpeg)\n',
    '    else:\n',
    '        shutil.copy2(str(final_raw), str(final_out))\n',
    '\n',
    '    dur_total = get_duration(final_out, ffmpeg)\n',
    '    mins, secs = divmod(int(dur_total), 60)\n',
    '\n',
    "    print(f\"\\n{'='*60}\")\n",
    '    print(f"  ✓ DONE!  {episode_id}")\n',
    '    print(f"  Duration : {mins}m {secs}s")\n',
    '    print(f"  Output   : {final_out}")\n',
    "    print(f\"{'='*60}\\n\")\n",
    '\n',
    '\n',
    'def _make_silence(path: Path, dur: float, ffmpeg: str) -> None:\n',
    '    """Generate a silent audio file of the given duration."""\n',
    '    subprocess.run(\n',
    '        [ffmpeg, "-y", "-f", "lavfi", "-i", f"anullsrc=r=44100:cl=mono",\n',
    '         "-t", str(dur), "-c:a", "aac", str(path)],\n',
    '        capture_output=True,\n',
    '    )\n',
    '\n',
    '\n',
    'if __name__ == "__main__":\n',
    '    main()\n',
]

with open('/sessions/busy-brave-franklin/mnt/video-bot-pipeline/auto_render.py', 'a', encoding='utf-8') as f:
    f.writelines(lines)

print(f"Appended {len(lines)} lines.")
