#!/usr/bin/env python3
"""
Secure credential setup wizard.
Guides through minimal credential entry, validates, stores in .env.
"""

import os
import sys
from pathlib import Path
from typing import Optional, Dict
import json

# Try to import requests for credential validation
try:
    import requests
except ImportError:
    print("⚠️ requests library not found. Run: pip install requests")
    sys.exit(1)

ENV_FILE = Path(__file__).parent / ".env"
PLATFORMS = {
    "etsy": {
        "vars": ["ETSY_TOKEN", "ETSY_SHOP_ID"],
        "test_url": "https://api.etsy.com/v3/application/shops/{ETSY_SHOP_ID}",
        "test_header": "x-api-key",
    },
    "depop": {
        "vars": ["DEPOP_TOKEN"],
        "test_url": "https://www.depop.com/api/v1/user/profile",
        "test_header": "Authorization",
        "test_header_format": "Bearer {DEPOP_TOKEN}",
    },
    "shopify": {
        "vars": ["SHOPIFY_TOKEN", "SHOPIFY_STORE_NAME"],
        "test_url": "https://{SHOPIFY_STORE_NAME}/admin/api/2024-01/shop.json",
        "test_header": "X-Shopify-Access-Token",
    },
    "woocommerce": {
        "vars": ["WOOCOMMERCE_URL", "WOOCOMMERCE_KEY", "WOOCOMMERCE_SECRET"],
        "test_url": "{WOOCOMMERCE_URL}/wp-json/wc/v3/system_status",
        "test_auth": "basic",
    },
    "buzz": {
        "vars": ["BUZZ_RELAY_URL", "BUZZ_PRIVATE_KEY"],
        "optional": True,
    },
}

def load_existing_env() -> Dict[str, str]:
    """Load existing .env file if it exists."""
    if ENV_FILE.exists():
        env_vars = {}
        with open(ENV_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, value = line.split("=", 1)
                    env_vars[key.strip()] = value.strip()
        return env_vars
    return {}

def prompt_for_credential(key: str, description: str = "", existing: Optional[str] = None) -> str:
    """Prompt user for a single credential."""
    prompt = f"\n{key}"
    if description:
        prompt += f" ({description})"
    if existing:
        prompt += f"\n  Current: {'*' * (len(existing) - 4)}{existing[-4:]}"
    prompt += "\n  Enter value or press Enter to skip: "

    value = input(prompt).strip()
    return value or existing or ""

def test_credential(platform: str, env_vars: Dict[str, str]) -> bool:
    """Test a credential against its platform API."""
    config = PLATFORMS.get(platform, {})
    if not config:
        return False

    print(f"\n  Testing {platform.upper()}...", end=" ", flush=True)

    # Check all required vars exist
    for var in config.get("vars", []):
        if var not in env_vars or not env_vars[var]:
            print(f"❌ Missing {var}")
            return False

    # Skip test for Buzz (no external API)
    if platform == "buzz":
        print("✓ Config present")
        return True

    try:
        url = config["test_url"]
        for var in config["vars"]:
            url = url.replace(f"{{{var}}}", env_vars[var])

        if platform == "woocommerce":
            response = requests.get(
                url,
                auth=(env_vars["WOOCOMMERCE_KEY"], env_vars["WOOCOMMERCE_SECRET"]),
                timeout=5
            )
        else:
            headers = {}
            if "test_header" in config:
                header_key = config["test_header"]
                header_value = env_vars[config["vars"][0]]
                if "test_header_format" in config:
                    header_value = config["test_header_format"].replace(
                        f"{{{config['vars'][0]}}}", header_value
                    )
                headers[header_key] = header_value

            response = requests.get(url, headers=headers, timeout=5)

        if response.status_code in [200, 400, 401]:
            if response.status_code == 200:
                print("✓")
                return True
            else:
                print(f"⚠️ Status {response.status_code} (check credentials)")
                return False
        else:
            print(f"❌ Status {response.status_code}")
            return False

    except requests.exceptions.Timeout:
        print("❌ Timeout (check URL/connection)")
        return False
    except Exception as e:
        print(f"❌ Error: {str(e)[:50]}")
        return False

def save_env(env_vars: Dict[str, str]):
    """Save environment variables to .env file."""
    with open(ENV_FILE, "w") as f:
        f.write("# Empire OS Environment Variables\n")
        f.write("# Generated by setup_credentials.py\n")
        f.write("# DO NOT COMMIT THIS FILE\n\n")

        for platform in PLATFORMS:
            if platform in env_vars:
                f.write(f"\n# {platform.upper()}\n")
                for var in PLATFORMS[platform]["vars"]:
                    if var in env_vars:
                        f.write(f"{var}={env_vars[var]}\n")

    print(f"\n✓ Saved to {ENV_FILE}")
    print("⚠️ DO NOT COMMIT .env to git — it's in .gitignore")

def main():
    """Main credential setup flow."""
    print("\n" + "=" * 60)
    print("Empire OS Credential Setup")
    print("=" * 60)
    print("\nThis wizard will guide you through credential entry.")
    print("Press Ctrl+C to exit without saving.")
    print("\nCredentials are stored in .env (not committed to git)")

    existing_env = load_existing_env()
    new_env = dict(existing_env)

    platforms_to_setup = []

    print("\n" + "=" * 60)
    print("Which platforms do you want to set up?")
    print("=" * 60)

    for platform in PLATFORMS:
        if PLATFORMS[platform].get("optional"):
            continue

        print(f"\n{platform.upper()}: ", end="")
        has_creds = all(var in existing_env and existing_env[var] for var in PLATFORMS[platform]["vars"])

        if has_creds:
            print(f"✓ Already configured")
            setup = input(f"  Reconfigure? (y/n): ").lower() == "y"
        else:
            setup = input(f"(y/n): ").lower() == "y"

        if setup:
            platforms_to_setup.append(platform)

    if not platforms_to_setup:
        print("\n✓ Nothing to configure.")
        return

    # Setup each platform
    for platform in platforms_to_setup:
        print(f"\n" + "=" * 60)
        print(f"{platform.upper()} CREDENTIALS")
        print("=" * 60)

        config = PLATFORMS[platform]

        for var in config["vars"]:
            existing = existing_env.get(var)
            description = {
                "ETSY_TOKEN": "OAuth token from etsy.com/developers",
                "ETSY_SHOP_ID": "Numeric shop ID (e.g., 12345678)",
                "DEPOP_TOKEN": "API token from depop.com/developer",
                "SHOPIFY_TOKEN": "Access token from Shopify admin",
                "SHOPIFY_STORE_NAME": "Your store name (e.g., my-store.myshopify.com)",
                "WOOCOMMERCE_URL": "Your store URL (e.g., https://mystore.com)",
                "WOOCOMMERCE_KEY": "Consumer key from WooCommerce settings",
                "WOOCOMMERCE_SECRET": "Consumer secret from WooCommerce settings",
            }.get(var, "")

            value = prompt_for_credential(var, description, existing)
            if value:
                new_env[var] = value

    # Test credentials
    print("\n" + "=" * 60)
    print("TESTING CREDENTIALS")
    print("=" * 60)

    for platform in platforms_to_setup:
        test_credential(platform, new_env)

    # Save
    print("\n" + "=" * 60)
    response = input("Save credentials? (y/n): ").lower()
    if response == "y":
        save_env(new_env)
        print("\n✓ Setup complete!")
        print("\nNext steps:")
        print("  1. START_AGENTS.bat  (launches all 5 agents)")
        print("  2. Add items to boss-listers-ai/data.json")
        print("  3. Watch Buzz at http://localhost:3000")
    else:
        print("\n✗ Credentials not saved.")

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n✗ Setup cancelled.")
        sys.exit(0)
