@echo off
cd /d C:\Users\jjard\claude\video-bot-pipeline\empire-os-patch\apps\empire-os-server
echo Starting Empire OS Server (port 3001)...
echo Using tsx from local node_modules...
node_modules\.bin\tsx.CMD server.ts
