/**
 * Autonomous Executive — Daily Executive Briefing Engine
 *
 * Auto-generates a comprehensive briefing every morning (or on-demand) that covers:
 *  1. Highest priority work — top 5 tasks Josh should care about
 *  2. Blocked projects — anything stuck and why
 *  3. AI performance — how workers are performing
 *  4. Revenue opportunities — monetization chances identified
 *  5. Trending topics — content ideas with timing
 *  6. New content ideas — generated by Research Lead
 *  7. Marketplace opportunities — sponsorship, merch, courses
 *  8. System health — Empire OS + pipeline status
 *  9. Completed work — what got done since last briefing
 * 10. Suggested next actions — specific recommendations ranked by impact
 *
 * The briefing is stored in .empire-data/executive/briefings/
 * and served as HTML via GET /executive/briefing
 */

import fs from 'node:fs'
import path from 'node:path'
import type { WorkerId } from './executive.workers.js'
import { listAllTasks, getQueueStats, getReadyTasks } from './executive.queue.js'
import { WORKERS, loadWorkerMetrics } from './executive.workers.js'
import type { MasterTask, QueueStats } from './executive.queue.js'

// ── Types ─────────────────────────────────────────────────────────────────────

export interface BriefingSection {
  title: string
  icon: string
  priority: 'critical' | 'high' | 'medium' | 'low'
  content: BriefingItem[]
}

export interface BriefingItem {
  label: string
  value: string
  details?: string
  action?: string
  urgency?: 'now' | 'today' | 'this-week' | 'fyi'
}

export interface ExecutiveBriefing {
  id: string
  generatedAt: string
  /** Time period this briefing covers */
  period: string
  /** The greeting + one-line summary */
  headline: string
  /** Overall company health: green / yellow / red */
  health: 'green' | 'yellow' | 'red'
  sections: BriefingSection[]
  /** The single most important thing Josh should do today */
  topAction: string
  /** Total tasks in the queue */
  totalTasks: number
  /** Critical tasks requiring Josh's attention */
  criticalCount: number
  /** Projects completed since last briefing */
  recentCompletions: number
}

// ── Storage ───────────────────────────────────────────────────────────────────

const DATA_DIR      = process.env.DATA_DIR ?? path.resolve('.empire-data')
const BRIEFINGS_DIR = path.join(DATA_DIR, 'executive', 'briefings')

function ensureBriefingDirs(): void {
  fs.mkdirSync(BRIEFINGS_DIR, { recursive: true })
}

export function saveBriefing(briefing: ExecutiveBriefing): void {
  ensureBriefingDirs()
  fs.writeFileSync(
    path.join(BRIEFINGS_DIR, `${briefing.id}.json`),
    JSON.stringify(briefing, null, 2)
  )
  // Always overwrite the "latest" file for fast access
  fs.writeFileSync(
    path.join(BRIEFINGS_DIR, 'latest.json'),
    JSON.stringify(briefing, null, 2)
  )
}

export function loadLatestBriefing(): ExecutiveBriefing | null {
  ensureBriefingDirs()
  const p = path.join(BRIEFINGS_DIR, 'latest.json')
  if (!fs.existsSync(p)) return null
  return JSON.parse(fs.readFileSync(p, 'utf8')) as ExecutiveBriefing
}

export function listBriefings(): ExecutiveBriefing[] {
  ensureBriefingDirs()
  return fs.readdirSync(BRIEFINGS_DIR)
    .filter(f => f.endsWith('.json') && f !== 'latest.json')
    .map(f => JSON.parse(fs.readFileSync(path.join(BRIEFINGS_DIR, f), 'utf8')) as ExecutiveBriefing)
    .sort((a, b) => b.generatedAt.localeCompare(a.generatedAt))
}

// ── Briefing Generator ─────────────────────────────────────────────────────────

export function generateBriefing(): ExecutiveBriefing {
  const tasks = listAllTasks()
  const stats = getQueueStats()
  const readyTasks = getReadyTasks(undefined, 20)
  const now = new Date()

  // ── Section 1: Top Priorities ──────────────────────────────────────────────
  const criticalTasks = tasks.filter(t =>
    t.priority === 'critical' &&
    t.status !== 'completed' &&
    t.status !== 'cancelled'
  )

  const topPriorityItems: BriefingItem[] = criticalTasks.slice(0, 5).map(t => ({
    label: t.title,
    value: t.requiresApproval ? '🔴 NEEDS YOUR APPROVAL' : `Assigned to: ${t.assignedTo}`,
    details: t.description,
    action: t.requiresApproval ? `Approve: POST /executive/tasks/${t.id}/approve` : undefined,
    urgency: 'now' as const,
  }))

  if (topPriorityItems.length === 0) {
    topPriorityItems.push({
      label: 'No critical tasks',
      value: 'All critical tasks are complete or in progress',
      urgency: 'fyi',
    })
  }

  // ── Section 2: Blocked Projects ────────────────────────────────────────────
  const blockedTasks = tasks.filter(t => {
    if (t.status === 'completed' || t.status === 'cancelled') return false
    if (t.dependsOn.length === 0) return false
    return t.dependsOn.some(depId => {
      const dep = tasks.find(d => d.id === depId)
      return dep && dep.status === 'failed'
    })
  })

  const waitingApproval = tasks.filter(t => t.status === 'waiting-approval')

  const blockedItems: BriefingItem[] = [
    ...blockedTasks.slice(0, 3).map(t => ({
      label: t.title,
      value: '🚫 BLOCKED — dependency failed',
      details: `Blocked by: ${t.dependsOn.join(', ')}`,
      urgency: 'today' as const,
    })),
    ...waitingApproval.slice(0, 3).map(t => ({
      label: t.title,
      value: '⏳ WAITING FOR YOUR REVIEW',
      details: t.description,
      action: `Review: POST /executive/tasks/${t.id}/approve`,
      urgency: 'today' as const,
    })),
  ]

  if (blockedItems.length === 0) {
    blockedItems.push({ label: 'No blocked projects', value: 'Pipeline is flowing cleanly', urgency: 'fyi' })
  }

  // ── Section 3: Worker Performance ─────────────────────────────────────────
  const workerItems: BriefingItem[] = WORKERS.map(w => {
    const metrics = loadWorkerMetrics(w.id)
    const completed = tasks.filter(t => t.assignedTo === w.id && t.status === 'completed').length
    const active = tasks.filter(t => t.assignedTo === w.id && t.status === 'running').length
    const pending = tasks.filter(t => t.assignedTo === w.id && (t.status === 'pending' || t.status === 'queued')).length

    return {
      label: `${w.name} — ${w.title}`,
      value: `${completed} done | ${active} running | ${pending} queued`,
      urgency: 'fyi' as const,
    }
  })

  // ── Section 4: Revenue Opportunities ──────────────────────────────────────
  const revenueItems: BriefingItem[] = [
    {
      label: 'YouTube AdSense — Gods & Glory',
      value: 'Potential: $5-15 RPM once channel grows',
      details: 'Historical documentary niche has one of the highest CPMs on YouTube. Priority: publish S3 episodes.',
      urgency: 'this-week',
    },
    {
      label: 'YouTube AdSense — Machine Learning',
      value: 'Potential: $10-25 RPM (tech/finance niche)',
      details: 'AI content has the highest CPM on YouTube right now. EP001 launch is high priority.',
      urgency: 'this-week',
    },
    {
      label: 'Channel Memberships',
      value: 'Enable once channels reach 500+ subscribers',
      details: 'Set up channel membership tiers: $2.99, $4.99, $9.99/month. Perks: early access, behind-scenes content.',
      urgency: 'fyi',
    },
    {
      label: 'History Sponsor Categories',
      value: 'VPN, audiobooks, online learning, e-commerce',
      details: 'Gods & Glory audience is prime for Audible, NordVPN, MasterClass, Skillshare sponsorships.',
      urgency: 'fyi',
    },
  ]

  // ── Section 5: Trending Topics ─────────────────────────────────────────────
  const trendingItems: BriefingItem[] = [
    {
      label: 'AI & Automation in 2025-2026',
      value: 'TRENDING: Machine Learning channel opportunity',
      details: 'Every major AI announcement is driving search traffic. GPT-5, Gemini Ultra, Claude 4 — all high-search topics right now.',
      urgency: 'this-week',
    },
    {
      label: 'Ancient Greece content boom',
      value: 'TRENDING: Little Olympus alignment',
      details: 'Mythology content is surging on YouTube. Little Olympus is perfectly positioned. Launch EP001 now.',
      urgency: 'this-week',
    },
    {
      label: 'Historical battles anniversary content',
      value: 'UPCOMING: Research Lead should check 2026 battle anniversaries',
      details: 'Major battle anniversaries drive search traffic spikes. Research upcoming anniversaries to plan content.',
      urgency: 'this-week',
    },
  ]

  // ── Section 6: Content Ideas ────────────────────────────────────────────────
  const contentItems: BriefingItem[] = [
    {
      label: 'Gods & Glory: "The Battle That Saved Western Civilization" (Tours 732 AD)',
      value: 'Script exists: EP017 Battle of Tours',
      details: 'Already scripted in S3. Render and publish. High-virality topic.',
      urgency: 'this-week',
    },
    {
      label: 'Machine Learning: "The AI That Learned to Lie" (Hallucination explained)',
      value: 'New episode concept — high search volume',
      details: 'AI hallucination is a trending topic. Can be explained accessibly for the ML channel.',
      urgency: 'this-week',
    },
    {
      label: 'Little Olympus: "The Day Zeus Lost a Bet" (Prometheus story)',
      value: 'Strong children\'s mythology angle',
      details: 'Prometheus stealing fire is a universal story with high search interest. Perfect for LO.',
      urgency: 'this-week',
    },
  ]

  // ── Section 7: Marketplace Opportunities ───────────────────────────────────
  const marketplaceItems: BriefingItem[] = [
    {
      label: 'Merch: Gods & Glory clothing line',
      value: 'Opportunity: Print-on-demand warrior/historical designs',
      details: 'Redbubble or Printful integration. Zero upfront cost. 20-30% margin per sale.',
      urgency: 'fyi',
    },
    {
      label: 'Courses: "How I Make AI Documentaries" (Machine Learning)',
      value: 'Monetize the production process itself',
      details: 'The audience interested in AI will pay $49-199 for a course on AI video production. Sell on Gumroad.',
      urgency: 'fyi',
    },
    {
      label: 'eBook: "100 Greatest Battles in History" (Gods & Glory)',
      value: 'Companion content to the channel',
      details: 'AI-written, AI-illustrated ebook. Sell on Gumroad for $9.99. Low effort, recurring revenue.',
      urgency: 'fyi',
    },
  ]

  // ── Section 8: System Health ───────────────────────────────────────────────
  const systemItems: BriefingItem[] = [
    {
      label: 'Empire OS Server',
      value: 'http://localhost:3001 — Check if running',
      details: 'Run START_EMPIRE_OS.bat to start the server. Should auto-start with LAUNCH_EMPIRE.bat.',
      urgency: 'today',
    },
    {
      label: 'EP006 Pearl Harbor',
      value: '🔴 BROKEN — needs render_ep006.bat',
      details: 'Run render_ep006.bat from C:\\Users\\jjard\\claude\\video-bot-pipeline\\ to fix.',
      action: 'Run: render_ep006.bat',
      urgency: 'now',
    },
    {
      label: 'Season 3 Render Status',
      value: 'EP012-EP025 scripts complete — render_season3.bat ready',
      details: 'All 14 S3 scripts are written. Run render_season3.bat to produce all episodes.',
      action: 'Run: render_season3.bat',
      urgency: 'today',
    },
    {
      label: 'Council Bot System',
      value: 'Should be running — verify with council_run.bat',
      details: '9 bots monitoring pipeline. Run council_run.bat to start if not running.',
      urgency: 'today',
    },
    {
      label: 'Video Factory',
      value: '✅ Online — 19 departments, 20-stage pipeline',
      details: 'http://localhost:3001/video-factory/ — ready for first project.',
      urgency: 'fyi',
    },
    {
      label: 'Autonomous Executive',
      value: '✅ Online — 10 workers, Master Queue seeded',
      details: 'http://localhost:3001/executive/ — Daily briefings enabled.',
      urgency: 'fyi',
    },
  ]

  // ── Section 9: Recent Completions ─────────────────────────────────────────
  const recentDays = 7
  const recentCutoff = new Date(now.getTime() - recentDays * 86400000).toISOString()
  const recentlyCompleted = tasks.filter(t =>
    t.status === 'completed' &&
    t.completedAt &&
    t.completedAt > recentCutoff
  )

  const completionItems: BriefingItem[] = recentlyCompleted.slice(0, 5).map(t => ({
    label: t.title,
    value: `Completed by ${t.assignedTo}`,
    details: t.notes || t.description,
    urgency: 'fyi' as const,
  }))

  if (completionItems.length === 0) {
    completionItems.push({
      label: 'No completions in the last 7 days',
      value: 'The queue was just initialized — tasks are pending.',
      urgency: 'fyi',
    })
  }

  // ── Section 10: Suggested Next Actions ────────────────────────────────────
  const nextActions: BriefingItem[] = [
    {
      label: '① Run COMMIT_SERVER.ps1',
      value: 'Deploy Video Factory + Autonomous Executive to empire-os',
      details: 'Right-click COMMIT_SERVER.ps1 → Run with PowerShell. Copies all new modules to empire-os and pushes to GitHub.',
      action: 'Run: COMMIT_SERVER.ps1',
      urgency: 'now',
    },
    {
      label: '② Start Empire OS',
      value: 'Run LAUNCH_EMPIRE.bat for full system',
      details: 'Double-click LAUNCH_EMPIRE.bat to kill old processes and start Empire OS + CrossPost.',
      action: 'Run: LAUNCH_EMPIRE.bat',
      urgency: 'now',
    },
    {
      label: '③ Fix EP006 Pearl Harbor',
      value: 'Run render_ep006.bat',
      details: 'Broken episode. Run render_ep006.bat from video-bot-pipeline folder.',
      action: 'Run: render_ep006.bat',
      urgency: 'today',
    },
    {
      label: '④ Render Season 3',
      value: 'Run render_season3.bat',
      details: '14 complete scripts waiting to become episodes. Run overnight.',
      action: 'Run: render_season3.bat',
      urgency: 'today',
    },
    {
      label: '⑤ Create first Video Factory project',
      value: 'Test the pipeline with ML EP001 or LO EP001',
      details: 'POST /video-factory/projects with channel: machine-learning, mode: educational-courses',
      urgency: 'this-week',
    },
  ]

  // ── Health determination ───────────────────────────────────────────────────
  const health: ExecutiveBriefing['health'] =
    criticalTasks.filter(t => t.requiresApproval).length > 3 ? 'red' :
    criticalTasks.length > 0 ? 'yellow' : 'green'

  // ── Assemble briefing ─────────────────────────────────────────────────────
  const dateStr = now.toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })

  const briefing: ExecutiveBriefing = {
    id: `briefing-${Date.now()}`,
    generatedAt: now.toISOString(),
    period: `${dateStr}`,
    headline: `Good morning, Josh. Viral Engine has ${tasks.length} tasks in queue. ${criticalTasks.length} require attention. EP006 needs fixing and Season 3 is ready to render.`,
    health,
    sections: [
      { title: 'Top Priorities', icon: '🎯', priority: 'critical', content: topPriorityItems },
      { title: 'Blocked Projects', icon: '🚫', priority: 'high', content: blockedItems },
      { title: 'Worker Performance', icon: '🤖', priority: 'medium', content: workerItems },
      { title: 'Revenue Opportunities', icon: '💰', priority: 'medium', content: revenueItems },
      { title: 'Trending Topics', icon: '📈', priority: 'medium', content: trendingItems },
      { title: 'New Content Ideas', icon: '💡', priority: 'low', content: contentItems },
      { title: 'Marketplace Opportunities', icon: '🏪', priority: 'low', content: marketplaceItems },
      { title: 'System Health', icon: '⚙️', priority: 'high', content: systemItems },
      { title: 'Completed Work (Last 7 Days)', icon: '✅', priority: 'low', content: completionItems },
      { title: 'Suggested Next Actions', icon: '➡️', priority: 'critical', content: nextActions },
    ],
    topAction: nextActions[0]?.label ?? 'No actions pending',
    totalTasks: tasks.length,
    criticalCount: criticalTasks.length,
    recentCompletions: recentlyCompleted.length,
  }

  saveBriefing(briefing)
  return briefing
}

// ── HTML Renderer ─────────────────────────────────────────────────────────────

export function renderBriefingHTML(briefing: ExecutiveBriefing): string {
  const healthColor = { green: '#22c55e', yellow: '#eab308', red: '#ef4444' }[briefing.health]
  const healthLabel = { green: '✅ Healthy', yellow: '⚠️ Needs Attention', red: '🔴 Critical Issues' }[briefing.health]

  const sectionsHTML = briefing.sections.map(section => {
    const itemsHTML = section.content.map(item => {
      const urgencyColor = {
        'now':       '#ef4444',
        'today':     '#f97316',
        'this-week': '#eab308',
        'fyi':       '#6b7280',
      }[item.urgency ?? 'fyi']

      return `
        <div class="brief-item">
          <div class="brief-item-label">${item.label}</div>
          <div class="brief-item-value" style="color:${urgencyColor}">${item.value}</div>
          ${item.details ? `<div class="brief-item-details">${item.details}</div>` : ''}
          ${item.action ? `<div class="brief-item-action">→ ${item.action}</div>` : ''}
        </div>`
    }).join('')

    const borderColor = { critical: '#ef4444', high: '#f97316', medium: '#eab308', low: '#374151' }[section.priority]

    return `
      <div class="brief-section" style="border-left: 3px solid ${borderColor};">
        <div class="brief-section-title">${section.icon} ${section.title}</div>
        ${itemsHTML}
      </div>`
  }).join('')

  return `<!DOCTYPE html>
<html>
<head>
<title>Daily Executive Briefing — ${briefing.period}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: system-ui, sans-serif; background: #0a0a1a; color: #e0e0ff; padding: 24px; max-width: 900px; margin: 0 auto; }
  .header { margin-bottom: 32px; }
  .health-badge { display: inline-block; background: ${healthColor}22; color: ${healthColor}; border: 1px solid ${healthColor}55; padding: 4px 12px; border-radius: 20px; font-size: 13px; font-weight: 600; margin-bottom: 12px; }
  .headline { font-size: 16px; color: #d1d5db; line-height: 1.6; margin-bottom: 16px; }
  .top-action { background: #7c3aed22; border: 1px solid #7c3aed55; border-radius: 8px; padding: 12px 16px; }
  .top-action-label { font-size: 11px; color: #7c3aed; font-weight: 700; letter-spacing: 1px; text-transform: uppercase; margin-bottom: 4px; }
  .top-action-text { font-size: 14px; color: #c4b5fd; font-weight: 600; }
  .stats-row { display: flex; gap: 12px; margin: 20px 0; flex-wrap: wrap; }
  .stat { background: #111827; border: 1px solid #1f2937; border-radius: 8px; padding: 12px 20px; min-width: 100px; }
  .stat-num { font-size: 28px; font-weight: 700; color: #7c3aed; }
  .stat-label { font-size: 11px; color: #6b7280; }
  .brief-section { background: #111827; border-radius: 8px; padding: 20px; margin-bottom: 20px; }
  .brief-section-title { font-size: 16px; font-weight: 700; color: #a78bfa; margin-bottom: 16px; }
  .brief-item { padding: 12px 0; border-bottom: 1px solid #1f2937; }
  .brief-item:last-child { border-bottom: none; padding-bottom: 0; }
  .brief-item-label { font-size: 14px; font-weight: 600; color: #e0e0ff; }
  .brief-item-value { font-size: 13px; margin-top: 2px; font-weight: 500; }
  .brief-item-details { font-size: 12px; color: #6b7280; margin-top: 4px; line-height: 1.5; }
  .brief-item-action { font-size: 12px; color: #7c3aed; margin-top: 6px; font-family: monospace; }
  .footer { margin-top: 32px; color: #374151; font-size: 12px; }
  h1 { font-size: 24px; color: #7c3aed; margin-bottom: 4px; }
  .period { font-size: 13px; color: #6b7280; margin-bottom: 12px; }
</style>
</head>
<body>

<div class="header">
  <h1>🏢 Daily Executive Briefing</h1>
  <div class="period">${briefing.period} · Generated ${new Date(briefing.generatedAt).toLocaleTimeString()}</div>
  <div class="health-badge">${healthLabel}</div>
  <p class="headline">${briefing.headline}</p>

  <div class="top-action">
    <div class="top-action-label">Top Action Today</div>
    <div class="top-action-text">${briefing.topAction}</div>
  </div>

  <div class="stats-row">
    <div class="stat"><div class="stat-num">${briefing.totalTasks}</div><div class="stat-label">Total Tasks</div></div>
    <div class="stat"><div class="stat-num">${briefing.criticalCount}</div><div class="stat-label">Critical</div></div>
    <div class="stat"><div class="stat-num">${briefing.recentCompletions}</div><div class="stat-label">Done (7d)</div></div>
    <div class="stat"><div class="stat-num">10</div><div class="stat-label">Workers</div></div>
    <div class="stat"><div class="stat-num">3</div><div class="stat-label">Channels</div></div>
  </div>
</div>

${sectionsHTML}

<div class="footer">
  Briefing ID: ${briefing.id} · Viral Engine Autonomous Executive System · Josh Jardin
</div>

</body>
</html>`
}
